### ISSUE TITLE
Unable to Delete User Created Word

### ISSUE THREAD

**Issue by RenSchuon** [peeley/lucy#110]
The confirmation prompt screen comes up but if you press yes it does not do anything. No does work as expected

**Comment by lvs-vong** [comment]
That's weird. It works on my end.
It successfully deletes the word, but keeps the tile's color.

**Comment by ElizabethSchuon** [comment]
It happened on an iPad, and only when trying to delete a word that a user made

**Comment by RenSchuon** [comment]
This seems to not be a problem now
